/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.github.seggan.myxal.kotlin-application-conventions")
}

dependencies {
    implementation(project(":runtime"))
}

application {
    // Define the main class for the application.
    mainClass.set("io.github.seggan.myxal.app.Main")
}
