/*
 * This file was generated by the Gradle 'init' task.
 */

import java.nio.file.Files
import java.nio.file.Path as JPath

plugins {
    id("io.github.seggan.myxal.kotlin-application-conventions")

    id("com.github.johnrengelman.shadow").version("7.1.2")
    id("antlr")
}

dependencies {
    implementation(project(":runtime"))

    implementation("org.ow2.asm:asm:9.3")
    implementation("org.ow2.asm:asm-commons:9.3")
    implementation("org.ow2.asm:asm-util:9.3")

    implementation("com.guardsquare:proguard-base:7.2.1")

    antlr("org.antlr:antlr4:4.10.1")
}

application {
    // Define the main class for the application.
    mainClass.set("io.github.seggan.myxal.app.Main")
}

tasks.generateGrammarSource {
    maxHeapSize = "128m"
    val path = JPath.of("$buildDir/generated-src/")
    val fullPath = path.resolve("antlr/main/io/github/seggan/myxal/antlr/")
    doFirst {
        Files.createDirectories(fullPath)
    }
    arguments = arguments + listOf(
        "-lib", fullPath.toAbsolutePath().toString(),
        "-visitor",
        "-no-listener",
        "-encoding", "UTF-8",
        "-package", "io.github.seggan.myxal.antlr"
    )
    outputDirectory = fullPath.toFile()
}

java.sourceSets["main"].java {
    srcDir("$buildDir/generated-src/antlr/main/")
}
