/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `cpp-library`
}

val pathToLLVM = "C:\\Program Files\\LLVM"

library {
    dependencies {
        implementation(files("$pathToLLVM\\lib\\LLVM-C.lib"))
    }
}